### ISSUE TITLE
MegaRaptor Bites when dropping gore

### ISSUE THREAD

**Issue by Silemara** [BoBAdministration/QA-Bug-Reports#200] opened 2021-12-26 22:48 UTC
**Describe the Bug**
Gore dropped on a player causes bite damage, but when picked up and dropped again it doesn't cause damage, effect only applies to new dinos in the area effecting them only the first time its dropped on them. Oddly while I was able to do this consistently I appeared to be the only one that could

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.  Logged into Dedicated Testing 3
2. Spawned in a Mega raptor, and grow to 1.2
3. pick up small mega raptor gore
4. when placing the gore down on top of another player with the drop button I "BITE" without actually attempting to attack

**Expected behavior**
Gore when drop is placed on ground with no further actions or animations

**Actual behavior**
Gore dropped on a player causes bite damage and bleed effect

**Screenshots & Video**
https://youtu.be/lB8HVjegD3o
![mega talents](https://user-images.githubusercontent.com/96402288/147421717-2722856a-d808-472f-a13f-807e6805ecae.png)

**Branch Version**
Test

**Character Information**
Megaraptor, speed with some combat, 1.209 (force grown)

**Additional Information**
AP canvas map

**Comment by Predatoria** [comment] 2022-01-27 22:46
I haven't been able to reproduce this.  I'm wondering if it got fixed by something else since it's been up a while.

**Closed by Predatoria** 2022-01-27 22:46 UTC
