### ISSUE TITLE
Dinos that are forced grown on Volcano_Bay do not gain points.

### ISSUE THREAD

**Issue by finchye** [BoBAdministration/QA-Bug-Reports#159] opened 2021-12-22 02:26 UTC
**Describe the Bug**
Dinos that are forced grown on Volcano_Bay do not gain points.

**To Reproduce**
1. Log onto any server using the Volcano_Bay map.
2. Set growth to 1.2.
3. Open talent tree to notice that no talent points have been added.

**Expected behavior**
1.2 Dinos should have 25 points when force grown.

**Actual behavior**
1.2 Force grown dinos do not gain any points.

**Screenshots & Video**
https://www.youtube.com/watch?v=B39YMC7l-50&ab_channel=finch

**Branch Version**
Live.

**Character Information**
1.2 ptera.

**Additional Information**
Volcano_Bay.

**Comment by tinystarpaws** [comment] 2021-12-22 02:32
Cannot reproduce this.
![image](https://user-images.githubusercontent.com/38923098/147025154-076742ef-66c1-4b4d-85cf-06e0c3a0f2f0.png)
![image](https://user-images.githubusercontent.com/38923098/147025203-37d60a1e-927d-4a4b-ba0d-51b87afa6d0a.png)

**Comment by tinystarpaws** [comment] 2021-12-22 03:22
Spoke w/ submitter; most likely a config file error. Closing.

**Closed by tinystarpaws** 2021-12-22 03:22 UTC
Labels: can't reproduce, gameplay bug, live branch
