### ISSUE TITLE
Itchy few to no walking/swimming sounds when sprinting. (May be related to #225: Lurdu)

### ISSUE THREAD

**Issue by Rehlik** [BoBAdministration/QA-Bug-Reports#226] opened 2022-01-10 15:36 UTC
**Describe the Bug**
While sprinting with an Itchy on live or tester branch, walking and swimming sounds are almost non existent.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log on to Live or Tester server.
2. Spawn as Itchy
3. Walk/sprint.
4. No sounds emit while sprinting.

**Expected behavior**
Sounds!

**Actual behavior**
While sprinting no sounds emit (including swimming).

**Screenshots & Video**
https://youtu.be/a3gVF3Z-DGA

**Branch Version**
Tester AND Live.

**Character Information**
Itchy, 0.45, 1.2, 1.8 tested. Sneaky with zero talents and every point between tested.

**Additional Information**
Forest Island, Titania, clear weather.

**Comment by Rehlik** [comment] 2022-01-10 16:20
Spoke with some Mosa main's on live servers, and it appears the bug is also happening with normal swimming on Mosa's, but not while sprinting. Repeated it myself, but since I don't main Mosa I didn't know if that was always the case.

**Comment by IsJoshIE** [comment] 2022-01-11 15:22
#185

**Comment by IsJoshIE** [comment] 2022-01-11 15:23
Duplicate of #185

**Comment by Predatoria** [comment] 2022-01-20 19:16
I was able to reproduce and fix this in UE

**Closed** 2022-01-20 22:47 UTC
Labels: Fixed-PendingTesting
