### ISSUE TITLE
Pachy Injury Charge

### ISSUE THREAD

**Issue by Vallyhalla** [BoBAdministration/QA-Bug-Reports#250] opened 2022-02-12 02:35 UTC
**Describe the Bug**
Depending on the size, Pachy's animation for charging stops and it shows its limping animation to another player depending on the injury. Started testing as 1.2, and the bug started happening with 60% injury. Zunaria on her end it looked normal, but for me it was an extremely fast limp. But when grown to 2.0, the bug started showing for me when Zunaria had 45% injury. All of this is with no Unbreakable invested and no inherits.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Logged into Dedicated Testing 2.
2. Partner spawned a Pachy in, grew to 1.2
3. Entered points, no Unbreakable.
4. Got various amounts of injury until the limping animation started.
5. At 60% amount of injury start charging.
6. For the player watching, the Pachy is limping very quickly while charging.
7. Grew to 2.0.
8. Still no Unbreakable.
9. Tried various amounts of injury.
10. At 45% injury started charging.
11. For the player watching, the Pachy is limping very quickly while charging.

**Expected behavior**
While charging with any amount of injury the charging animation should play for players watching.

**Actual behavior**
While charging with 45%-70% injury, at growths 1.2 and again at 2.0, the animation turns into a fast limp but still produces the charge damage/injury/knockback.

**Screenshots & Video**
https://www.youtube.com/watch?v=V5JaXvHaIbM  (2.0 pachy, 70% injury)

**Branch Version**
Both. Bug was brought up from an experience on Live, and reproduced on Tester.

**Character Information**
First round the Pachy was 1.2, and second round it was 2.0. No Unbreakable inherited or invested.

**Additional Information**
Didn't test what happens when Unbreakable is invested into.

**Comment by Predatoria** [comment] 2022-02-18 21:44
Should be fixed, couldn't reproduce though

**Closed by Predatoria** 2022-02-18 21:44 UTC
