### ISSUE TITLE
Megaraptor double jump backwards

### ISSUE THREAD

**Issue by Revstiel** [BoBAdministration/QA-Bug-Reports#221] opened 2022-01-08 20:17 UTC
**Describe the Bug**
if you press your specific ability button and spam the space bar you do a double pounce backwards. You have to click it perfectly will add recording to be able to repeat it, the momentum keeps them going backwards

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. ex. Logged into Dedicated Testing 3
2. Spawn in as megaraptor
3. Use the ability key
4. Right when you land press the space bar again
5. You have double jumped backwards

**Expected behavior**
Should not double jump backwards

**Actual behavior**
You are able to double jump backwards

**Screenshots & Video**
https://user-images.githubusercontent.com/96402095/148658659-b46a4280-20aa-44ac-bb37-f166a539863d.mp4

**Branch Version**
Tester

**Character Information**
1.2 with pure speed talents 3/3 swift, nimble, endurance, sl, sf then 2/3 combat

**Additional Information**
Clear day

**Comment by Predatoria** [comment] 2022-01-27 21:40
duplicate of 172.  I fixed it

**Closed by Predatoria** 2022-01-27 21:40 UTC
