### ISSUE TITLE
Some Items duplicating or counting wrong

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#323] opened 2022-05-26 18:43 UTC
**Describe the Bug**
Some Items are duplicating in the file but not physically on the map after a restart or for a handful of items just as you are placing them. Some of them also disappear in the middle of placing them and I noticed that the ones that do are the ones that they are some of the ones that are duplicating. 

**To Reproduce**
1. Log onto any server that has map permissions
2. Place more than 1 Cube of the same type (5 in this test)
3. In this test we placed 10 of every asset (other than cubes and rocks in this test)
4. Attempt to Place Juniper Tree 01 and 02, smAcacia TreeA and B
6. Observe Juniper and Acacia doubling/stacking numbers incorectly and disappearing acts while placing( The disappearing doesn't happen consistently so could not get it to do it again...however might be attached to why they duped.) 
7. Restart server
8. Observe Cube amounts have increased in file but not physically
9. Observe numbers of assets that duplicated (In this test Juniper Tree 02, Acacia Tree A, Sm_Seaweed C, Sponge C though others might on further tests)

**Expected behavior**
For the item count to be accurate.

**Actual behavior**
Causing the file size to be larger than the actual asset amounts

**Screenshots & Video**
https://youtu.be/eDVW16Y4Zhs

**Branch Version**
Both (Live for test)

**Character Information**
N/A

**Additional Information**
RS Canvas

**Comment by Zi-Mom** [comment] 2022-05-26 23:58
![image](https://user-images.githubusercontent.com/88993347/170602635-b77f0922-54b6-4f10-85fb-4e090c2e7f3a.png)
![image](https://user-images.githubusercontent.com/88993347/170602645-98cad861-333e-4c2f-889b-89c423958894.png)


Before and after Dupes of items on another server

**Comment by Predatoria** [comment] 2022-05-31 20:07
+Couldn't reproduce but maybe fixed (issue 323): Juniper Tree 01 and 02 were both referencing the same mesh, so they caused strange behavior with the foliage placement tool.  I fixed the mesh ref.

**Comment by Predatoria** [comment] 2022-05-31 21:24
This may have gotten fixed alongside issue 322.  I'm going to go ahead and close this.

**Closed by Predatoria** 2022-05-31 21:24 UTC
